version: "3.7"
services:
  db:
    image: mysql
    container_name: mysql-eagle-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: wilsongomes123
      MYSQL_DATABASE: eagle_cms
      MYSQL_USER: eagle_cms
      MYSQL_PASSWORD: eagle_cms
    volumes:
      - ./docker/cache/data:/var/lib/mysql
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci', "--default-authentication-plugin=mysql_native_password"]
  app:
    build: ./docker/app
    container_name: php-eagle-container
    restart: always
    volumes:
      - ./src:/var/www/html
    ports:
      - "8080:80"
    depends_on: 
      - db
